/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface InkWell {
    'color': string;
  }
}

declare global {


  interface HTMLInkWellElement extends Components.InkWell, HTMLStencilElement {}
  var HTMLInkWellElement: {
    prototype: HTMLInkWellElement;
    new (): HTMLInkWellElement;
  };
  interface HTMLElementTagNameMap {
    'ink-well': HTMLInkWellElement;
  }
}

declare namespace LocalJSX {
  interface InkWell extends JSXBase.HTMLAttributes<HTMLInkWellElement> {
    'color'?: string;
  }

  interface IntrinsicElements {
    'ink-well': InkWell;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


